/*
 * Copyright © 2024 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * 边距常量
 *
 * @author photowey
 * @since 2024/08/20
 * @version 1.0.0
 */

// 边距
export const PADDING_S = 10;

export const PADDING_M = 16;

export const PADDING = PADDING_M;

export const PADDING_L = 20;

// 圆角
export const BORDER_RADIUS_S = 4;

export const BORDER_RADIUS_M = 8;

export const BORDER_RADIUS = BORDER_RADIUS_M;

export const BORDER_RADIUS_L = 12;

// 阴影
export const SHADOW_RADIUS = 7.8;
